/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK_DOT = 1,
  anon_sym_COLON = 2,
  anon_sym_AMP = 3,
  anon_sym_RBRACK = 4,
  anon_sym_article = 5,
  anon_sym_summary = 6,
  anon_sym_extractor_DASHai_DASHchat = 7,
  anon_sym_note = 8,
  aux_sym_bit_type_token1 = 9,
  anon_sym_bitmark_DASH_DASH = 10,
  anon_sym_bitmark_PLUS_PLUS = 11,
  anon_sym_image = 12,
  anon_sym_video = 13,
  anon_sym_LBRACK_BANG = 14,
  anon_sym_LBRACK_QMARK = 15,
  anon_sym_LBRACK_ = 16,
  anon_sym___ = 17,
  anon_sym_EQ_EQ = 18,
  anon_sym_EQ_EQ_PIPElatex_PIPE = 19,
  anon_sym_EQ_EQ_PIPEsuperscript_PIPE = 20,
  anon_sym_EQ_EQ_PIPEsubscript_PIPE = 21,
  sym_text = 22,
  sym_document = 23,
  sym__block = 24,
  sym_bit_block = 25,
  sym_bit_header = 26,
  sym_bit_type = 27,
  sym_text_format = 28,
  sym_resource_type = 29,
  sym_block_tag = 30,
  sym__inline = 31,
  sym_instruction_block_tag = 32,
  sym_hint_block_tag = 33,
  sym_bitmark_minus_text = 34,
  sym_gap = 35,
  sym_italic = 36,
  sym_formula_inline = 37,
  sym_superscript = 38,
  sym_subscript = 39,
  sym_plain_text = 40,
  aux_sym_document_repeat1 = 41,
  aux_sym_bit_block_repeat1 = 42,
  aux_sym_bitmark_minus_text_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK_DOT] = "[.",
  [anon_sym_COLON] = ":",
  [anon_sym_AMP] = "&",
  [anon_sym_RBRACK] = "]",
  [anon_sym_article] = "article",
  [anon_sym_summary] = "summary",
  [anon_sym_extractor_DASHai_DASHchat] = "extractor-ai-chat",
  [anon_sym_note] = "note",
  [aux_sym_bit_type_token1] = "bit_type_token1",
  [anon_sym_bitmark_DASH_DASH] = "bitmark--",
  [anon_sym_bitmark_PLUS_PLUS] = "bitmark++",
  [anon_sym_image] = "image",
  [anon_sym_video] = "video",
  [anon_sym_LBRACK_BANG] = "[!",
  [anon_sym_LBRACK_QMARK] = "[\?",
  [anon_sym_LBRACK_] = "[_",
  [anon_sym___] = "__",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_EQ_EQ_PIPElatex_PIPE] = "==|latex|",
  [anon_sym_EQ_EQ_PIPEsuperscript_PIPE] = "==|superscript|",
  [anon_sym_EQ_EQ_PIPEsubscript_PIPE] = "==|subscript|",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_bit_block] = "bit_block",
  [sym_bit_header] = "bit_header",
  [sym_bit_type] = "bit_type",
  [sym_text_format] = "text_format",
  [sym_resource_type] = "resource_type",
  [sym_block_tag] = "block_tag",
  [sym__inline] = "_inline",
  [sym_instruction_block_tag] = "instruction_block_tag",
  [sym_hint_block_tag] = "hint_block_tag",
  [sym_bitmark_minus_text] = "bitmark_minus_text",
  [sym_gap] = "gap",
  [sym_italic] = "italic",
  [sym_formula_inline] = "formula_inline",
  [sym_superscript] = "superscript",
  [sym_subscript] = "subscript",
  [sym_plain_text] = "plain_text",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_bit_block_repeat1] = "bit_block_repeat1",
  [aux_sym_bitmark_minus_text_repeat1] = "bitmark_minus_text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK_DOT] = anon_sym_LBRACK_DOT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_article] = anon_sym_article,
  [anon_sym_summary] = anon_sym_summary,
  [anon_sym_extractor_DASHai_DASHchat] = anon_sym_extractor_DASHai_DASHchat,
  [anon_sym_note] = anon_sym_note,
  [aux_sym_bit_type_token1] = aux_sym_bit_type_token1,
  [anon_sym_bitmark_DASH_DASH] = anon_sym_bitmark_DASH_DASH,
  [anon_sym_bitmark_PLUS_PLUS] = anon_sym_bitmark_PLUS_PLUS,
  [anon_sym_image] = anon_sym_image,
  [anon_sym_video] = anon_sym_video,
  [anon_sym_LBRACK_BANG] = anon_sym_LBRACK_BANG,
  [anon_sym_LBRACK_QMARK] = anon_sym_LBRACK_QMARK,
  [anon_sym_LBRACK_] = anon_sym_LBRACK_,
  [anon_sym___] = anon_sym___,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_EQ_EQ_PIPElatex_PIPE] = anon_sym_EQ_EQ_PIPElatex_PIPE,
  [anon_sym_EQ_EQ_PIPEsuperscript_PIPE] = anon_sym_EQ_EQ_PIPEsuperscript_PIPE,
  [anon_sym_EQ_EQ_PIPEsubscript_PIPE] = anon_sym_EQ_EQ_PIPEsubscript_PIPE,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_bit_block] = sym_bit_block,
  [sym_bit_header] = sym_bit_header,
  [sym_bit_type] = sym_bit_type,
  [sym_text_format] = sym_text_format,
  [sym_resource_type] = sym_resource_type,
  [sym_block_tag] = sym_block_tag,
  [sym__inline] = sym__inline,
  [sym_instruction_block_tag] = sym_instruction_block_tag,
  [sym_hint_block_tag] = sym_hint_block_tag,
  [sym_bitmark_minus_text] = sym_bitmark_minus_text,
  [sym_gap] = sym_gap,
  [sym_italic] = sym_italic,
  [sym_formula_inline] = sym_formula_inline,
  [sym_superscript] = sym_superscript,
  [sym_subscript] = sym_subscript,
  [sym_plain_text] = sym_plain_text,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_bit_block_repeat1] = aux_sym_bit_block_repeat1,
  [aux_sym_bitmark_minus_text_repeat1] = aux_sym_bitmark_minus_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_article] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_summary] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extractor_DASHai_DASHchat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_note] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_bit_type_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_bitmark_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bitmark_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_image] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_video] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_PIPElatex_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_PIPEsuperscript_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_PIPEsubscript_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_bit_block] = {
    .visible = true,
    .named = true,
  },
  [sym_bit_header] = {
    .visible = true,
    .named = true,
  },
  [sym_bit_type] = {
    .visible = true,
    .named = true,
  },
  [sym_text_format] = {
    .visible = true,
    .named = true,
  },
  [sym_resource_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__inline] = {
    .visible = false,
    .named = true,
  },
  [sym_instruction_block_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_hint_block_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_bitmark_minus_text] = {
    .visible = true,
    .named = true,
  },
  [sym_gap] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_formula_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_superscript] = {
    .visible = true,
    .named = true,
  },
  [sym_subscript] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bit_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bitmark_minus_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bit_type = 1,
  field_gap = 2,
  field_hint = 3,
  field_instruction = 4,
  field_resource = 5,
  field_text_format = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bit_type] = "bit_type",
  [field_gap] = "gap",
  [field_hint] = "hint",
  [field_instruction] = "instruction",
  [field_resource] = "resource",
  [field_text_format] = "text_format",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_bit_type, 1},
  [1] =
    {field_instruction, 1},
  [2] =
    {field_hint, 1},
  [3] =
    {field_gap, 1},
  [4] =
    {field_bit_type, 1},
    {field_text_format, 3},
  [6] =
    {field_bit_type, 1},
    {field_resource, 3},
  [8] =
    {field_bit_type, 1},
    {field_resource, 5},
    {field_text_format, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
};

static const TSCharacterRange sym_text_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', ')'}, {'+', '<'}, {'>', 'Z'}, {'\\', '\\'}, {'^', '^'}, {'`', '{'},
  {'}', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(52);
      ADVANCE_MAP(
        '&', 55,
        ':', 54,
        '=', 6,
        '[', 1,
        ']', 56,
        '_', 10,
        'a', 100,
        'b', 89,
        'e', 112,
        'i', 93,
        'n', 98,
        's', 111,
        'v', 87,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('c' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '|') ADVANCE(162);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(152);
      if (lookahead == '.') ADVANCE(53);
      if (lookahead == '?') ADVANCE(153);
      if (lookahead == '_') ADVANCE(154);
      END_STATE();
    case 2:
      if (lookahead == '&') ADVANCE(55);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == ']') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(132);
      if (lookahead == 'e') ADVANCE(142);
      if (lookahead == 'n') ADVANCE(130);
      if (lookahead == 's') ADVANCE(141);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 3:
      if (lookahead == '+') ADVANCE(147);
      END_STATE();
    case 4:
      if (lookahead == '+') ADVANCE(3);
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(145);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(157);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(156);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == ']') ADVANCE(56);
      if (lookahead == '_') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '[' &&
          lookahead != '|') ADVANCE(162);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(47);
      END_STATE();
    case 10:
      if (lookahead == '_') ADVANCE(155);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 14:
      if (lookahead == 'b') ADVANCE(39);
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'b') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(30);
      if (lookahead == 'v') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(37);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(148);
      END_STATE();
    case 23:
      if (lookahead == 'g') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'k') ADVANCE(4);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(11);
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 'm') ADVANCE(12);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(150);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 46:
      if (lookahead == 'x') ADVANCE(48);
      END_STATE();
    case 47:
      if (lookahead == '|') ADVANCE(29);
      END_STATE();
    case 48:
      if (lookahead == '|') ADVANCE(158);
      END_STATE();
    case 49:
      if (lookahead == '|') ADVANCE(160);
      END_STATE();
    case 50:
      if (lookahead == '|') ADVANCE(159);
      END_STATE();
    case 51:
      if (eof) ADVANCE(52);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '[') ADVANCE(1);
      if (lookahead == ']') ADVANCE(56);
      if (lookahead == '_') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(51);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '|') ADVANCE(162);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACK_DOT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_article);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_article);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_summary);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_summary);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_extractor_DASHai_DASHchat);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_extractor_DASHai_DASHchat);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_note);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_note);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '+') ADVANCE(161);
      if (lookahead == '-') ADVANCE(66);
      if (lookahead == '_') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '-') ADVANCE(146);
      if (lookahead == '_') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '-') ADVANCE(78);
      if (lookahead == '_') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '-') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '-') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '-') ADVANCE(75);
      if (lookahead == '_') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'a') ADVANCE(85);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'a') ADVANCE(79);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'a') ADVANCE(101);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'a') ADVANCE(102);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'a') ADVANCE(90);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'a') ADVANCE(106);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'c') ADVANCE(92);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'c') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'c') ADVANCE(109);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'd') ADVANCE(84);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'e') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'e') ADVANCE(149);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'e') ADVANCE(97);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'g') ADVANCE(82);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'h') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'i') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'i') ADVANCE(77);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'i') ADVANCE(110);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'i') ADVANCE(67);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'k') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'l') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'm') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'm') ADVANCE(73);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'm') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'm') ADVANCE(95);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'o') ADVANCE(151);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'o') ADVANCE(105);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'o') ADVANCE(103);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'r') ADVANCE(108);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'r') ADVANCE(91);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'r') ADVANCE(113);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'r') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'r') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 't') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 't') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 't') ADVANCE(104);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 't') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 't') ADVANCE(99);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 't') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'u') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'x') ADVANCE(107);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == 'y') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'a') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'a') ADVANCE(121);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'a') ADVANCE(134);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'a') ADVANCE(138);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'c') ADVANCE(127);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'c') ADVANCE(124);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'c') ADVANCE(140);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'e') ADVANCE(58);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'h') ADVANCE(118);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'i') ADVANCE(119);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'i') ADVANCE(68);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'l') ADVANCE(123);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'm') ADVANCE(129);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'm') ADVANCE(117);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'o') ADVANCE(137);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'o') ADVANCE(135);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'r') ADVANCE(136);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'r') ADVANCE(116);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'r') ADVANCE(143);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'r') ADVANCE(69);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 't') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 't') ADVANCE(122);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 't') ADVANCE(62);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 't') ADVANCE(133);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 't') ADVANCE(131);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'u') ADVANCE(128);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'x') ADVANCE(139);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == 'y') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(aux_sym_bit_type_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(144);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_bitmark_DASH_DASH);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_bitmark_DASH_DASH);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_bitmark_PLUS_PLUS);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_image);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_image);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(anon_sym_video);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(anon_sym_video);
      if (lookahead == '_') ADVANCE(144);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_LBRACK_BANG);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(anon_sym_LBRACK_QMARK);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(anon_sym_LBRACK_);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym___);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      if (lookahead == '|') ADVANCE(29);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_PIPElatex_PIPE);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_PIPEsuperscript_PIPE);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_PIPEsubscript_PIPE);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '+') ADVANCE(147);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(162);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_text);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(162);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 51},
  [3] = {.lex_state = 51},
  [4] = {.lex_state = 51},
  [5] = {.lex_state = 51},
  [6] = {.lex_state = 51},
  [7] = {.lex_state = 51},
  [8] = {.lex_state = 51},
  [9] = {.lex_state = 51},
  [10] = {.lex_state = 51},
  [11] = {.lex_state = 51},
  [12] = {.lex_state = 51},
  [13] = {.lex_state = 51},
  [14] = {.lex_state = 51},
  [15] = {.lex_state = 51},
  [16] = {.lex_state = 51},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 51},
  [25] = {.lex_state = 51},
  [26] = {.lex_state = 51},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 51},
  [30] = {.lex_state = 51},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 51},
  [33] = {.lex_state = 51},
  [34] = {.lex_state = 51},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK_DOT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_article] = ACTIONS(1),
    [anon_sym_summary] = ACTIONS(1),
    [anon_sym_extractor_DASHai_DASHchat] = ACTIONS(1),
    [anon_sym_note] = ACTIONS(1),
    [aux_sym_bit_type_token1] = ACTIONS(1),
    [anon_sym_bitmark_DASH_DASH] = ACTIONS(1),
    [anon_sym_bitmark_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_image] = ACTIONS(1),
    [anon_sym_video] = ACTIONS(1),
    [anon_sym_LBRACK_BANG] = ACTIONS(1),
    [anon_sym_LBRACK_QMARK] = ACTIONS(1),
    [anon_sym_LBRACK_] = ACTIONS(1),
    [anon_sym___] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ_PIPElatex_PIPE] = ACTIONS(1),
    [anon_sym_EQ_EQ_PIPEsuperscript_PIPE] = ACTIONS(1),
    [anon_sym_EQ_EQ_PIPEsubscript_PIPE] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(39),
    [sym__block] = STATE(19),
    [sym_bit_block] = STATE(19),
    [sym_bit_header] = STATE(2),
    [aux_sym_document_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK_DOT] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACK_BANG,
    ACTIONS(11), 1,
      anon_sym_LBRACK_QMARK,
    ACTIONS(13), 1,
      anon_sym_LBRACK_,
    ACTIONS(15), 1,
      anon_sym___,
    ACTIONS(17), 1,
      anon_sym_EQ_EQ,
    ACTIONS(19), 1,
      sym_text,
    ACTIONS(7), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
    STATE(7), 2,
      sym_instruction_block_tag,
      sym_hint_block_tag,
    STATE(3), 8,
      sym_block_tag,
      sym__inline,
      sym_gap,
      sym_italic,
      sym_formula_inline,
      sym_superscript,
      sym_subscript,
      aux_sym_bit_block_repeat1,
  [37] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACK_BANG,
    ACTIONS(11), 1,
      anon_sym_LBRACK_QMARK,
    ACTIONS(13), 1,
      anon_sym_LBRACK_,
    ACTIONS(15), 1,
      anon_sym___,
    ACTIONS(17), 1,
      anon_sym_EQ_EQ,
    ACTIONS(23), 1,
      sym_text,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
    STATE(7), 2,
      sym_instruction_block_tag,
      sym_hint_block_tag,
    STATE(4), 8,
      sym_block_tag,
      sym__inline,
      sym_gap,
      sym_italic,
      sym_formula_inline,
      sym_superscript,
      sym_subscript,
      aux_sym_bit_block_repeat1,
  [74] = 9,
    ACTIONS(27), 1,
      anon_sym_LBRACK_BANG,
    ACTIONS(30), 1,
      anon_sym_LBRACK_QMARK,
    ACTIONS(33), 1,
      anon_sym_LBRACK_,
    ACTIONS(36), 1,
      anon_sym___,
    ACTIONS(39), 1,
      anon_sym_EQ_EQ,
    ACTIONS(42), 1,
      sym_text,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
    STATE(7), 2,
      sym_instruction_block_tag,
      sym_hint_block_tag,
    STATE(4), 8,
      sym_block_tag,
      sym__inline,
      sym_gap,
      sym_italic,
      sym_formula_inline,
      sym_superscript,
      sym_subscript,
      aux_sym_bit_block_repeat1,
  [111] = 1,
    ACTIONS(45), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [122] = 1,
    ACTIONS(47), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [133] = 1,
    ACTIONS(49), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [144] = 1,
    ACTIONS(51), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [155] = 1,
    ACTIONS(53), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [166] = 1,
    ACTIONS(55), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [177] = 1,
    ACTIONS(57), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [188] = 1,
    ACTIONS(59), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [199] = 1,
    ACTIONS(61), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [210] = 1,
    ACTIONS(63), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [221] = 1,
    ACTIONS(65), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [232] = 1,
    ACTIONS(67), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK_DOT,
      anon_sym_LBRACK_BANG,
      anon_sym_LBRACK_QMARK,
      anon_sym_LBRACK_,
      anon_sym___,
      anon_sym_EQ_EQ,
      sym_text,
  [243] = 3,
    ACTIONS(71), 1,
      sym_text,
    STATE(17), 1,
      aux_sym_bitmark_minus_text_repeat1,
    ACTIONS(69), 5,
      anon_sym_RBRACK,
      anon_sym___,
      anon_sym_EQ_EQ_PIPElatex_PIPE,
      anon_sym_EQ_EQ_PIPEsuperscript_PIPE,
      anon_sym_EQ_EQ_PIPEsubscript_PIPE,
  [257] = 4,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      anon_sym_LBRACK_DOT,
    STATE(2), 1,
      sym_bit_header,
    STATE(18), 3,
      sym__block,
      sym_bit_block,
      aux_sym_document_repeat1,
  [272] = 4,
    ACTIONS(5), 1,
      anon_sym_LBRACK_DOT,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_bit_header,
    STATE(18), 3,
      sym__block,
      sym_bit_block,
      aux_sym_document_repeat1,
  [287] = 2,
    STATE(23), 1,
      sym_bit_type,
    ACTIONS(81), 5,
      anon_sym_article,
      anon_sym_summary,
      anon_sym_extractor_DASHai_DASHchat,
      anon_sym_note,
      aux_sym_bit_type_token1,
  [298] = 5,
    ACTIONS(83), 1,
      anon_sym_EQ_EQ_PIPElatex_PIPE,
    ACTIONS(85), 1,
      anon_sym_EQ_EQ_PIPEsuperscript_PIPE,
    ACTIONS(87), 1,
      anon_sym_EQ_EQ_PIPEsubscript_PIPE,
    ACTIONS(89), 1,
      sym_text,
    STATE(17), 1,
      aux_sym_bitmark_minus_text_repeat1,
  [314] = 1,
    ACTIONS(91), 3,
      anon_sym_COLON,
      anon_sym_AMP,
      anon_sym_RBRACK,
  [320] = 3,
    ACTIONS(93), 1,
      anon_sym_COLON,
    ACTIONS(95), 1,
      anon_sym_AMP,
    ACTIONS(97), 1,
      anon_sym_RBRACK,
  [330] = 3,
    ACTIONS(89), 1,
      sym_text,
    ACTIONS(99), 1,
      anon_sym___,
    STATE(17), 1,
      aux_sym_bitmark_minus_text_repeat1,
  [340] = 3,
    ACTIONS(101), 1,
      sym_text,
    STATE(30), 1,
      aux_sym_bitmark_minus_text_repeat1,
    STATE(40), 1,
      sym_bitmark_minus_text,
  [350] = 3,
    ACTIONS(101), 1,
      sym_text,
    STATE(30), 1,
      aux_sym_bitmark_minus_text_repeat1,
    STATE(41), 1,
      sym_bitmark_minus_text,
  [360] = 2,
    STATE(35), 1,
      sym_text_format,
    ACTIONS(103), 2,
      anon_sym_bitmark_DASH_DASH,
      anon_sym_bitmark_PLUS_PLUS,
  [368] = 2,
    STATE(38), 1,
      sym_resource_type,
    ACTIONS(105), 2,
      anon_sym_image,
      anon_sym_video,
  [376] = 3,
    ACTIONS(107), 1,
      sym_text,
    STATE(32), 1,
      aux_sym_bitmark_minus_text_repeat1,
    STATE(42), 1,
      sym_plain_text,
  [386] = 3,
    ACTIONS(89), 1,
      sym_text,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
    STATE(17), 1,
      aux_sym_bitmark_minus_text_repeat1,
  [396] = 2,
    STATE(43), 1,
      sym_resource_type,
    ACTIONS(105), 2,
      anon_sym_image,
      anon_sym_video,
  [404] = 3,
    ACTIONS(89), 1,
      sym_text,
    ACTIONS(111), 1,
      anon_sym_RBRACK,
    STATE(17), 1,
      aux_sym_bitmark_minus_text_repeat1,
  [414] = 2,
    ACTIONS(113), 1,
      sym_text,
    STATE(21), 1,
      aux_sym_bitmark_minus_text_repeat1,
  [421] = 2,
    ACTIONS(115), 1,
      sym_text,
    STATE(24), 1,
      aux_sym_bitmark_minus_text_repeat1,
  [428] = 2,
    ACTIONS(117), 1,
      anon_sym_AMP,
    ACTIONS(119), 1,
      anon_sym_RBRACK,
  [435] = 1,
    ACTIONS(121), 2,
      anon_sym_AMP,
      anon_sym_RBRACK,
  [440] = 1,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
  [444] = 1,
    ACTIONS(125), 1,
      anon_sym_RBRACK,
  [448] = 1,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
  [452] = 1,
    ACTIONS(129), 1,
      anon_sym_RBRACK,
  [456] = 1,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
  [460] = 1,
    ACTIONS(133), 1,
      anon_sym_RBRACK,
  [464] = 1,
    ACTIONS(135), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 133,
  [SMALL_STATE(8)] = 144,
  [SMALL_STATE(9)] = 155,
  [SMALL_STATE(10)] = 166,
  [SMALL_STATE(11)] = 177,
  [SMALL_STATE(12)] = 188,
  [SMALL_STATE(13)] = 199,
  [SMALL_STATE(14)] = 210,
  [SMALL_STATE(15)] = 221,
  [SMALL_STATE(16)] = 232,
  [SMALL_STATE(17)] = 243,
  [SMALL_STATE(18)] = 257,
  [SMALL_STATE(19)] = 272,
  [SMALL_STATE(20)] = 287,
  [SMALL_STATE(21)] = 298,
  [SMALL_STATE(22)] = 314,
  [SMALL_STATE(23)] = 320,
  [SMALL_STATE(24)] = 330,
  [SMALL_STATE(25)] = 340,
  [SMALL_STATE(26)] = 350,
  [SMALL_STATE(27)] = 360,
  [SMALL_STATE(28)] = 368,
  [SMALL_STATE(29)] = 376,
  [SMALL_STATE(30)] = 386,
  [SMALL_STATE(31)] = 396,
  [SMALL_STATE(32)] = 404,
  [SMALL_STATE(33)] = 414,
  [SMALL_STATE(34)] = 421,
  [SMALL_STATE(35)] = 428,
  [SMALL_STATE(36)] = 435,
  [SMALL_STATE(37)] = 440,
  [SMALL_STATE(38)] = 444,
  [SMALL_STATE(39)] = 448,
  [SMALL_STATE(40)] = 452,
  [SMALL_STATE(41)] = 456,
  [SMALL_STATE(42)] = 460,
  [SMALL_STATE(43)] = 464,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bit_block, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bit_block, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bit_block_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bit_block_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bit_block_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bit_block_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bit_block_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bit_block_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bit_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bit_header, 7, 0, 7),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_tag, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_gap, 3, 0, 4),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bit_header, 3, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction_block_tag, 3, 0, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_formula_inline, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_superscript, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hint_block_tag, 3, 0, 3),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subscript, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bit_header, 5, 0, 5),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bit_header, 5, 0, 6),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bitmark_minus_text_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bitmark_minus_text_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bit_type, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bitmark_minus_text, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_text, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_format, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource_type, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [127] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bitmark(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bitmark",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
